### PR TITLE
Feature/lw cocoapods

### PR DESCRIPTION
**Pull request by LoganWright**
This PR removes all submodule dependencies and updates the project to use cocoapods.  I specified versions that matched where the submodule head was at in the submodules.  We can update versions later, but for now I'm just focusing on getting pods setup.

Just in case you haven't used cocoapods before:
- Always open the `.xcworkspace` file.  The project file will no longer build.
- Run `cd path/to/project && pod install`

Then, you should be good to go.

Let me know if you'd prefer anything else added to this.

@justinanderson : I assigned this one to you just in case you wanted to verify the project first, I can give it to Ross or someone else if you prefer.

### CODE REVIEW

**Comment by LoganWright** [comment]
@justinanderson - In my current PR, the `Pods/` folder is in the `.gitignore`, which means a user has to have cocoapods setup on their computer, and they have to run `pod install`.  You mentioned in the meeting that you'd like the project to be something that someone could just clone the repo, or download the project and build straight off.  If we include the `Pods/` folder, then other users won't be required to have cocoapods and there's no extra step between downloading and pulling.

Let me know if you'd like me to add the folder to the PR and I can do that no problem!

Best,

Logan

**Comment by justinanderson** [comment]
@LoganWright That looks alright to me, though I'd like Ross to review it too since I don't have experience with CocoaPods. We'll want to update README.markdown to mention the new build steps.

**Comment by rosslebeau** [comment]
@LoganWright Looks mostly good, I think the Podfile should specify versions for all the pods though. There are a couple without versions, and I don't want to be accidentally pulling a breaking change. Then let's include the Pods/ folder and update the README, and it's good to go.

We should take the time to fork and make internal Pod specs for the remaining external code we have modified (e.g. SMCalloutView)...probably lets do this next week.

**Comment by justinanderson** [comment]
@LoganWright @rosslebeau We should be able to get rid of some things in Externals too. We shouldn't need ZBar anymore, for one.

**Pull request merged**
